services:
    fe-service:
        container_name: url-shortener-fe-service
        build:
            context: ./
            dockerfile: Dockerfile.production
        # extra_hosts:
        #     - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8002}:80'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            # depends_on:
            #     - be-service
        restart: always
        networks:
            - url-shortener-network
        # environment:
        #     WWWUSER: '${WWWUSER}'
        #     LARAVEL_SAIL: 1
        #     XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        #     XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        #     IGNITION_LOCAL_SITES_PATH: '${PWD}'
        # volumes:
        #     - './url-shortener-fe:/var/www/html/url-shortener-fe'
networks:
    url-shortener-network:
        external: true
